{"timestamp":"2025-07-06T10:08:16.858030","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:08:21.953469","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:08:21.953754","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:08:21.953988","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:08:21.955551","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:08:52.739182","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:08:56.857913","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:08:56.858148","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:08:56.858302","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:08:56.858684","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:09:27.817758","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:09:31.952573","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:09:31.952940","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:09:31.953201","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:09:31.953766","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:10:02.074427","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:10:06.212905","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:10:06.213149","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:10:06.213421","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:10:06.213980","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:10:36.558105","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:10:40.699415","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:10:40.699859","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:10:40.700122","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:10:40.700763","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:11:11.507442","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:11:15.649228","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:11:15.649592","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:11:15.649855","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:11:15.650351","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:11:45.813625","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:11:49.944591","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:11:49.944932","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:11:49.945221","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:11:49.945784","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:12:20.111886","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:12:24.242077","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:12:24.242415","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:12:24.242669","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:12:24.243256","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:12:54.494455","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:12:58.645140","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:12:58.645499","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:12:58.645696","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:12:58.646118","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:13:29.072353","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:13:33.199182","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:13:33.199529","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:13:33.199726","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:13:33.200185","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:14:04.050985","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:14:08.184843","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:14:08.185310","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:14:08.185511","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:14:08.186072","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:14:38.398412","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:14:42.512584","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:14:42.512850","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:14:42.513070","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:14:42.513530","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:15:13.517006","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:15:17.613415","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:15:17.613773","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:15:17.613967","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:15:17.614569","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:15:47.857133","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:15:51.999822","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:15:52.000192","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:15:52.000387","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:15:52.001110","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:16:22.371391","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:16:26.505755","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:16:26.506131","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:16:26.506332","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:16:26.506932","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:16:57.035074","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:17:01.177217","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:17:01.177591","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:17:01.177766","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:17:01.178216","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:17:32.080589","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:17:36.265605","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:17:36.266063","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:17:36.266225","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:17:36.266768","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:18:06.999860","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:18:11.105550","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:18:11.105880","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:18:11.106088","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:18:11.106529","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:18:41.883274","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:18:46.016604","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:18:46.016996","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:18:46.017222","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:18:46.017715","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:19:17.126421","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:19:21.251768","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:19:21.252104","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:19:21.252307","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:19:21.252810","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:19:51.533866","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:19:55.711565","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:19:55.712349","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:19:55.712722","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:19:55.714504","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:20:26.093520","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:20:30.238985","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:20:30.239468","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:20:30.239743","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:20:30.241325","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:21:00.494325","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:21:04.638822","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:21:04.639219","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:21:04.639430","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:21:04.640015","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:21:34.983634","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:21:39.137540","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:21:39.137942","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:21:39.138144","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:21:39.138673","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:22:09.482706","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:22:13.617907","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:22:13.618432","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:22:13.618647","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:22:13.619183","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:22:44.006505","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:22:48.132527","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:22:48.132804","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:22:48.132966","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:22:48.133351","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:23:18.940143","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:23:23.102027","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:23:23.102244","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:23:23.102423","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:23:23.102799","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:23:53.676444","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:23:59.353597","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:23:59.354007","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:23:59.354199","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:23:59.355169","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:24:30.442666","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:24:34.572791","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:24:34.573139","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:24:34.573460","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:24:34.573963","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:25:04.957190","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:25:09.082597","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:25:09.082824","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:25:09.082962","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:25:09.083458","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:25:39.772935","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:25:43.913874","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:25:43.914186","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:25:43.914392","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:25:43.914843","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:26:14.144616","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:26:18.281850","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:26:18.282221","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:26:18.282513","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:26:18.283101","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:26:48.736705","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:26:52.914376","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:26:52.914836","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:26:52.915044","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:26:52.915842","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-06T10:27:23.871367","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-06T10:27:28.021595","level":"warning","event":"DNS lookup failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:27:28.021888","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (0)","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:27:28.022149","level":"error","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure","logger":"kafka.conn"}
{"timestamp":"2025-07-06T10:27:28.022565","level":"error","event":"Failed to import: /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag","error_detail":[{"exc_type":"NoBrokersAvailable","exc_value":"NoBrokersAvailable","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":394,"name":"parse"},{"filename":"<frozen importlib._bootstrap_external>","lineno":999,"name":"exec_module"},{"filename":"<frozen importlib._bootstrap>","lineno":488,"name":"_call_with_frames_removed"},{"filename":"/opt/airflow/dags/airdag.py","lineno":4,"name":"<module>"},{"filename":"/opt/airflow/dags/data_producer.py","lineno":9,"name":"<module>"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py","lineno":481,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":262,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py","lineno":1074,"name":"check_version"}],"is_group":false,"exceptions":[]}]}
